import type { NextPage } from "next";
import Head from "next/head";

import Posts from "../components/Post/Posts";
import { getPostsData } from "../services";

const Home: NextPage<{ posts: String[] | any[] }> = (props) => {
  return (
    <>
      <Head>
        <title>Dev Telegraph</title>
        <meta name="description" content="Generated by Tolgahan" />
      </Head>

      <div className="w-full h-full ">
        {/* main */}
        <Posts posts={props.posts} />
      </div>
    </>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const posts = await getPostsData();

  return {
    props: {
      posts,
    },
  };
};
