import type { NextPage } from "next";
import Head from "next/head";

import Header from "../components/Header";
import Aside from "../components/Aside";
import Posts from "../components/Post/Posts";
import { getPostsData } from "../services";

const Home: NextPage<{ posts: String[] }> = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-full bg-main-background">
        {/* header */}
        <Header />

        {/* main */}
        <main className="w-full h-full">
          <Aside />

          <Posts posts={props.posts} />
        </main>
      </div>
    </>
  );
};

export default Home;

export const getStaticProps = async () => {
  const posts = await getPostsData();

  return {
    props: {
      posts,
    },
  };
};
